// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQfUjX02jQSQ209oLzRKsf7plDpoYO0qs',
    appId: '1:495040475612:web:781a4b3df155887bf11f19',
    messagingSenderId: '495040475612',
    projectId: 'password-manager-fef0a',
    authDomain: 'password-manager-fef0a.firebaseapp.com',
    storageBucket: 'password-manager-fef0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvtQElnHfzuxEg0nLU1fm02-D2B6ZdmwU',
    appId: '1:495040475612:android:1b5c5725b8a2de35f11f19',
    messagingSenderId: '495040475612',
    projectId: 'password-manager-fef0a',
    storageBucket: 'password-manager-fef0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsJjRaskhiOKW10udgfn4JBeTy3XMm3c',
    appId: '1:495040475612:ios:6fec2754f2a97028f11f19',
    messagingSenderId: '495040475612',
    projectId: 'password-manager-fef0a',
    storageBucket: 'password-manager-fef0a.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsJjRaskhiOKW10udgfn4JBeTy3XMm3c',
    appId: '1:495040475612:ios:6fec2754f2a97028f11f19',
    messagingSenderId: '495040475612',
    projectId: 'password-manager-fef0a',
    storageBucket: 'password-manager-fef0a.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQfUjX02jQSQ209oLzRKsf7plDpoYO0qs',
    appId: '1:495040475612:web:735f36737d05fbaff11f19',
    messagingSenderId: '495040475612',
    projectId: 'password-manager-fef0a',
    authDomain: 'password-manager-fef0a.firebaseapp.com',
    storageBucket: 'password-manager-fef0a.firebasestorage.app',
  );
}
